#!/bin/bash

# Add missing keys to EN.JSON
jq '. + {
  "general": "General",
  "appearance": "Appearance",
  "fontSize": "Font Size",
  "layoutMode": "Layout Mode",
  "defaultCurrency": "Default Currency",
  "small": "Small",
  "medium": "Medium",
  "large": "Large",
  "compact": "Compact",
  "expanded": "Expanded",
  "configureAppPreferences": "Configure application preferences",
  "selectCurrency": "Select currency",
  "defaultCurrencyDescription": "Default currency used for prices and invoices",
  "selectedCurrency": "Selected currency",
  "selectSize": "Select size",
  "modifyTextSize": "Modify text size in the application",
  "selectLayout": "Select layout",
  "chooseLayoutMode": "Choose between compact or expanded layout",
  "preview": "Preview",
  "changesAppliedAfterSave": "Changes will be applied after saving",
  "saveAllSettings": "Save All Settings",
  "close": "Close",
  "errorLoadingSettings": "Error loading settings",
  "errorSavingSettings": "Error saving settings",
  "connectionSuccessful": "Connection successful",
  "connectionError": "Connection error",
  "invalidApiKey": "Invalid API key",
  "apiKeyReset": "API key reset to default",
  "apiKeyStoredLocally": "API key is stored only in browser and never sent to external servers",
  "howToGetApiKey": "How to get your API key",
  "goToGoogleAIStudio": "Go to Google AI Studio",
  "loginWithGoogle": "Login with your Google Cloud account",
  "clickGetApiKey": "Click \"Get API Key\" or \"Create API Key\"",
  "copyAndPasteKey": "Copy the API key and paste it above",
  "openGoogleAIStudio": "Open Google AI Studio",
  "resetToDefault": "Reset to Default Key",
  "optional": "Optional",
  "enterPriceApiKey": "Enter PriceAPI key (optional)",
  "priceApiKeyDescription": "Use your personal key for more daily requests. If empty, uses default key.",
  "testing": "Testing",
  "testConnection": "Test Connection",
  "howToGetPriceApiKey": "How to get PriceAPI key",
  "goToPriceApi": "Go to priceapi.com",
  "createFreeAccount": "Create a free account",
  "copyYourApiKey": "Copy your personal API key",
  "pasteInField": "Paste it in the field above",
  "openPriceApi": "Open PriceAPI.com",
  "supabaseActive": "Supabase connection active and working",
  "supabaseConfigured": "Supabase configured automatically",
  "usingCustomKey": "Using custom key (unlimited account)",
  "usingDefaultKey": "Using default key (limits: 15 requests/minute)"
}' src/locales/en.json > src/locales/en.json.tmp && mv src/locales/en.json.tmp src/locales/en.json

# Add missing keys to ES.JSON
jq '. + {
  "general": "General",
  "appearance": "Apariencia",
  "fontSize": "Tamaño de Fuente",
  "layoutMode": "Modo de Diseño",
  "defaultCurrency": "Moneda Predeterminada",
  "small": "Pequeño",
  "medium": "Mediano",
  "large": "Grande",
  "compact": "Compacto",
  "expanded": "Expandido",
  "configureAppPreferences": "Configurar preferencias de la aplicación",
  "selectCurrency": "Seleccionar moneda",
  "defaultCurrencyDescription": "Moneda predeterminada utilizada para precios y facturas",
  "selectedCurrency": "Moneda seleccionada",
  "selectSize": "Seleccionar tamaño",
  "modifyTextSize": "Modificar el tamaño del texto en la aplicación",
  "selectLayout": "Seleccionar diseño",
  "chooseLayoutMode": "Elegir entre diseño compacto o expandido",
  "preview": "Vista previa",
  "changesAppliedAfterSave": "Los cambios se aplicarán después de guardar",
  "saveAllSettings": "Guardar Todas las Configuraciones",
  "close": "Cerrar",
  "errorLoadingSettings": "Error al cargar la configuración",
  "errorSavingSettings": "Error al guardar la configuración",
  "connectionSuccessful": "Conexión exitosa",
  "connectionError": "Error de conexión",
  "invalidApiKey": "Clave API no válida",
  "apiKeyReset": "Clave API restablecida al valor predeterminado",
  "apiKeyStoredLocally": "La clave API se almacena solo en el navegador y nunca se envía a servidores externos",
  "howToGetApiKey": "Cómo obtener tu clave API",
  "goToGoogleAIStudio": "Ve a Google AI Studio",
  "loginWithGoogle": "Inicia sesión con tu cuenta de Google Cloud",
  "clickGetApiKey": "Haz clic en \"Obtener clave API\" o \"Crear clave API\"",
  "copyAndPasteKey": "Copia la clave API y pégala arriba",
  "openGoogleAIStudio": "Abrir Google AI Studio",
  "resetToDefault": "Restablecer a la clave predeterminada",
  "optional": "Opcional",
  "enterPriceApiKey": "Ingresa la clave PriceAPI (opcional)",
  "priceApiKeyDescription": "Usa tu clave personal para más solicitudes diarias. Si está vacía, usa la clave predeterminada.",
  "testing": "Probando",
  "testConnection": "Probar Conexión",
  "howToGetPriceApiKey": "Cómo obtener la clave PriceAPI",
  "goToPriceApi": "Ve a priceapi.com",
  "createFreeAccount": "Crea una cuenta gratuita",
  "copyYourApiKey": "Copia tu clave API personal",
  "pasteInField": "Pégala en el campo de arriba",
  "openPriceApi": "Abrir PriceAPI.com",
  "supabaseActive": "Conexión Supabase activa y funcionando",
  "supabaseConfigured": "Supabase configurado automáticamente",
  "usingCustomKey": "Usando clave personalizada (cuenta ilimitada)",
  "usingDefaultKey": "Usando clave predeterminada (límites: 15 solicitudes/minuto)"
}' src/locales/es.json > src/locales/es.json.tmp && mv src/locales/es.json.tmp src/locales/es.json

# Add missing keys to FR.JSON
jq '. + {
  "general": "Général",
  "appearance": "Apparence",
  "fontSize": "Taille de Police",
  "layoutMode": "Mode de Mise en Page",
  "defaultCurrency": "Devise par Défaut",
  "small": "Petit",
  "medium": "Moyen",
  "large": "Grand",
  "compact": "Compact",
  "expanded": "Étendu",
  "configureAppPreferences": "Configurer les préférences de l'\''application",
  "selectCurrency": "Sélectionner la devise",
  "defaultCurrencyDescription": "Devise par défaut utilisée pour les prix et les factures",
  "selectedCurrency": "Devise sélectionnée",
  "selectSize": "Sélectionner la taille",
  "modifyTextSize": "Modifier la taille du texte dans l'\''application",
  "selectLayout": "Sélectionner la mise en page",
  "chooseLayoutMode": "Choisir entre mise en page compacte ou étendue",
  "preview": "Aperçu",
  "changesAppliedAfterSave": "Les modifications seront appliquées après l'\''enregistrement",
  "saveAllSettings": "Enregistrer Tous les Paramètres",
  "close": "Fermer",
  "errorLoadingSettings": "Erreur lors du chargement des paramètres",
  "errorSavingSettings": "Erreur lors de l'\''enregistrement des paramètres",
  "connectionSuccessful": "Connexion réussie",
  "connectionError": "Erreur de connexion",
  "invalidApiKey": "Clé API invalide",
  "apiKeyReset": "Clé API réinitialisée à la valeur par défaut",
  "apiKeyStoredLocally": "La clé API est stockée uniquement dans le navigateur et n'\''est jamais envoyée à des serveurs externes",
  "howToGetApiKey": "Comment obtenir votre clé API",
  "goToGoogleAIStudio": "Aller sur Google AI Studio",
  "loginWithGoogle": "Connectez-vous avec votre compte Google Cloud",
  "clickGetApiKey": "Cliquez sur \"Obtenir la clé API\" ou \"Créer une clé API\"",
  "copyAndPasteKey": "Copiez la clé API et collez-la ci-dessus",
  "openGoogleAIStudio": "Ouvrir Google AI Studio",
  "resetToDefault": "Réinitialiser à la clé par défaut",
  "optional": "Optionnel",
  "enterPriceApiKey": "Entrez la clé PriceAPI (optionnel)",
  "priceApiKeyDescription": "Utilisez votre clé personnelle pour plus de demandes quotidiennes. Si vide, utilise la clé par défaut.",
  "testing": "Test en cours",
  "testConnection": "Tester la Connexion",
  "howToGetPriceApiKey": "Comment obtenir la clé PriceAPI",
  "goToPriceApi": "Aller sur priceapi.com",
  "createFreeAccount": "Créer un compte gratuit",
  "copyYourApiKey": "Copiez votre clé API personnelle",
  "pasteInField": "Collez-la dans le champ ci-dessus",
  "openPriceApi": "Ouvrir PriceAPI.com",
  "supabaseActive": "Connexion Supabase active et fonctionnelle",
  "supabaseConfigured": "Supabase configuré automatiquement",
  "usingCustomKey": "Utilisation d'\''une clé personnalisée (compte illimité)",
  "usingDefaultKey": "Utilisation de la clé par défaut (limites: 15 requêtes/minute)"
}' src/locales/fr.json > src/locales/fr.json.tmp && mv src/locales/fr.json.tmp src/locales/fr.json

echo "✅ Missing keys added to EN, ES, FR"
