#!/bin/bash

# Add missing keys to DE.JSON
jq '. + {
  "general": "Allgemein",
  "appearance": "Aussehen",
  "fontSize": "Schriftgröße",
  "layoutMode": "Layout-Modus",
  "defaultCurrency": "Standardwährung",
  "small": "Klein",
  "medium": "Mittel",
  "large": "Groß",
  "compact": "Kompakt",
  "expanded": "Erweitert",
  "configureAppPreferences": "Anwendungseinstellungen konfigurieren",
  "selectCurrency": "Währung auswählen",
  "defaultCurrencyDescription": "Standardwährung für Preise und Rechnungen",
  "selectedCurrency": "Ausgewählte Währung",
  "selectSize": "Größe auswählen",
  "modifyTextSize": "Textgröße in der Anwendung ändern",
  "selectLayout": "Layout auswählen",
  "chooseLayoutMode": "Wählen Sie zwischen kompaktem oder erweitertem Layout",
  "preview": "Vorschau",
  "changesAppliedAfterSave": "Änderungen werden nach dem Speichern angewendet",
  "saveAllSettings": "Alle Einstellungen Speichern",
  "close": "Schließen",
  "errorLoadingSettings": "Fehler beim Laden der Einstellungen",
  "errorSavingSettings": "Fehler beim Speichern der Einstellungen",
  "connectionSuccessful": "Verbindung erfolgreich",
  "connectionError": "Verbindungsfehler",
  "invalidApiKey": "Ungültiger API-Schlüssel",
  "apiKeyReset": "API-Schlüssel auf Standard zurückgesetzt",
  "apiKeyStoredLocally": "Der API-Schlüssel wird nur im Browser gespeichert und niemals an externe Server gesendet",
  "howToGetApiKey": "So erhalten Sie Ihren API-Schlüssel",
  "goToGoogleAIStudio": "Gehen Sie zu Google AI Studio",
  "loginWithGoogle": "Melden Sie sich mit Ihrem Google Cloud-Konto an",
  "clickGetApiKey": "Klicken Sie auf \"API-Schlüssel abrufen\" oder \"API-Schlüssel erstellen\"",
  "copyAndPasteKey": "Kopieren Sie den API-Schlüssel und fügen Sie ihn oben ein",
  "openGoogleAIStudio": "Google AI Studio öffnen",
  "resetToDefault": "Auf Standardschlüssel zurücksetzen",
  "optional": "Optional",
  "enterPriceApiKey": "PriceAPI-Schlüssel eingeben (optional)",
  "priceApiKeyDescription": "Verwenden Sie Ihren persönlichen Schlüssel für mehr tägliche Anfragen. Wenn leer, wird der Standardschlüssel verwendet.",
  "testing": "Testen",
  "testConnection": "Verbindung Testen",
  "howToGetPriceApiKey": "So erhalten Sie den PriceAPI-Schlüssel",
  "goToPriceApi": "Gehen Sie zu priceapi.com",
  "createFreeAccount": "Erstellen Sie ein kostenloses Konto",
  "copyYourApiKey": "Kopieren Sie Ihren persönlichen API-Schlüssel",
  "pasteInField": "Fügen Sie ihn in das obige Feld ein",
  "openPriceApi": "PriceAPI.com öffnen",
  "supabaseActive": "Supabase-Verbindung aktiv und funktionsfähig",
  "supabaseConfigured": "Supabase automatisch konfiguriert",
  "usingCustomKey": "Verwenden eines benutzerdefinierten Schlüssels (unbegrenztes Konto)",
  "usingDefaultKey": "Verwenden des Standardschlüssels (Limits: 15 Anfragen/Minute)"
}' src/locales/de.json > src/locales/de.json.tmp && mv src/locales/de.json.tmp src/locales/de.json

# Add missing keys to LT.JSON
jq '. + {
  "general": "Bendra",
  "appearance": "Išvaizda",
  "fontSize": "Šrifto Dydis",
  "layoutMode": "Išdėstymo Režimas",
  "defaultCurrency": "Numatytoji Valiuta",
  "small": "Mažas",
  "medium": "Vidutinis",
  "large": "Didelis",
  "compact": "Kompaktiškas",
  "expanded": "Išplėstas",
  "configureAppPreferences": "Konfigūruoti programos nuostatas",
  "selectCurrency": "Pasirinkti valiutą",
  "defaultCurrencyDescription": "Numatytoji valiuta, naudojama kainoms ir sąskaitoms faktūroms",
  "selectedCurrency": "Pasirinkta valiuta",
  "selectSize": "Pasirinkti dydį",
  "modifyTextSize": "Keisti teksto dydį programoje",
  "selectLayout": "Pasirinkti išdėstymą",
  "chooseLayoutMode": "Pasirinkite kompaktišką arba išplėstą išdėstymą",
  "preview": "Peržiūra",
  "changesAppliedAfterSave": "Pakeitimai bus pritaikyti po išsaugojimo",
  "saveAllSettings": "Išsaugoti Visus Nustatymus",
  "close": "Uždaryti",
  "errorLoadingSettings": "Klaida įkeliant nustatymus",
  "errorSavingSettings": "Klaida išsaugant nustatymus",
  "connectionSuccessful": "Prisijungimas sėkmingas",
  "connectionError": "Prisijungimo klaida",
  "invalidApiKey": "Netinkamas API raktas",
  "apiKeyReset": "API raktas atstatytas į numatytąjį",
  "apiKeyStoredLocally": "API raktas saugomas tik naršyklėje ir niekada nesiunčiamas į išorinius serverius",
  "howToGetApiKey": "Kaip gauti savo API raktą",
  "goToGoogleAIStudio": "Eikite į Google AI Studio",
  "loginWithGoogle": "Prisijunkite su savo Google Cloud paskyra",
  "clickGetApiKey": "Spustelėkite \"Gauti API raktą\" arba \"Sukurti API raktą\"",
  "copyAndPasteKey": "Nukopijuokite API raktą ir įklijuokite jį aukščiau",
  "openGoogleAIStudio": "Atidaryti Google AI Studio",
  "resetToDefault": "Atstatyti į numatytąjį raktą",
  "optional": "Neprivaloma",
  "enterPriceApiKey": "Įveskite PriceAPI raktą (neprivaloma)",
  "priceApiKeyDescription": "Naudokite savo asmeninį raktą daugiau kasdienių užklausų. Jei tuščia, naudojamas numatytasis raktas.",
  "testing": "Testuojama",
  "testConnection": "Tikrinti Ryšį",
  "howToGetPriceApiKey": "Kaip gauti PriceAPI raktą",
  "goToPriceApi": "Eikite į priceapi.com",
  "createFreeAccount": "Sukurkite nemokamą paskyrą",
  "copyYourApiKey": "Nukopijuokite savo asmeninį API raktą",
  "pasteInField": "Įklijuokite jį į aukščiau esantį lauką",
  "openPriceApi": "Atidaryti PriceAPI.com",
  "supabaseActive": "Supabase ryšys aktyvus ir veikia",
  "supabaseConfigured": "Supabase sukonfigūruotas automatiškai",
  "usingCustomKey": "Naudojamas pasirinktinis raktas (neribota paskyra)",
  "usingDefaultKey": "Naudojamas numatytasis raktas (apribojimai: 15 užklausų/minutę)"
}' src/locales/lt.json > src/locales/lt.json.tmp && mv src/locales/lt.json.tmp src/locales/lt.json

echo "✅ Missing keys added to DE, LT"
