#!/bin/bash

# Backup the original file
cp src/lib/i18n.ts src/lib/i18n.ts.backup2

# Add Italian translations (already added above, but let's add English translations)
# Find line number for English section and add translations after line 860
sed -i '860a\    searchInvoicesPlaceholder: '\''Search invoices by number, supplier or notes...'\'',\n    clickToExpandYearMonth: '\''💡 Click on year/month to expand'\'',\n    goToSuppliersToAddInvoices: '\''Go to Suppliers section to add invoices'\'',\n    invoicesCount: '\''invoices'\'',\n    openingInvoiceManagement: '\''📂 Opening invoice management for'\'',\n    supplierDeletedWithInvoices: '\''✅ Supplier deleted together with'\'',\n    uploadSomeInvoicesToSeeStats: '\''Upload some invoices to see statistics'\'',\n    noProductsInInvoices: '\''No products in invoices'\'',\n    uploadPhotoDescription: '\''Upload photo (JPG, PNG) or PDF file of price lists, invoices or catalogs. AI will automatically recognize all products and prices. You can upload multiple files at once.'\'',\n    uploadSupplierDataDescription: '\''Upload photo or PDF with supplier data (business cards, contact lists, etc.). AI will automatically recognize the data.'\'',\n    uploadOrderDescription: '\''Upload photo or PDF of invoices, receipts or shopping lists. AI will automatically recognize products with quantities and prices to create the order.'\'',\n    from: '\''From'\'',\n    with: '\''with'\'',\n    together: '\''together'\'',' src/lib/i18n.ts

# Add Spanish translations after line 1108
sed -i '1108a\    searchInvoicesPlaceholder: '\''Buscar facturas por número, proveedor o notas...'\'',\n    clickToExpandYearMonth: '\''💡 Haz clic en año/mes para expandir'\'',\n    goToSuppliersToAddInvoices: '\''Ve a la sección de Proveedores para añadir facturas'\'',\n    invoicesCount: '\''facturas'\'',\n    openingInvoiceManagement: '\''📂 Abriendo gestión de facturas para'\'',\n    supplierDeletedWithInvoices: '\''✅ Proveedor eliminado junto con'\'',\n    uploadSomeInvoicesToSeeStats: '\''Sube algunas facturas para ver las estadísticas'\'',\n    noProductsInInvoices: '\''No hay productos en las facturas'\'',\n    uploadPhotoDescription: '\''Sube foto (JPG, PNG) o archivo PDF de listas de precios, facturas o catálogos. La IA reconocerá automáticamente todos los productos y precios. Puedes subir varios archivos a la vez.'\'',\n    uploadSupplierDataDescription: '\''Sube foto o PDF con datos de proveedores (tarjetas de visita, listas de contactos, etc.). La IA reconocerá automáticamente los datos.'\'',\n    uploadOrderDescription: '\''Sube foto o PDF de facturas, recibos o listas de compras. La IA reconocerá automáticamente los productos con cantidades y precios para crear el pedido.'\'',\n    from: '\''Desde'\'',\n    with: '\''con'\'',\n    together: '\''junto con'\'',' src/lib/i18n.ts

# Add French translations after line 1356
sed -i '1356a\    searchInvoicesPlaceholder: '\''Rechercher des factures par numéro, fournisseur ou notes...'\'',\n    clickToExpandYearMonth: '\''💡 Cliquez sur année/mois pour développer'\'',\n    goToSuppliersToAddInvoices: '\''Aller à la section Fournisseurs pour ajouter des factures'\'',\n    invoicesCount: '\''factures'\'',\n    openingInvoiceManagement: '\''📂 Ouverture de la gestion des factures pour'\'',\n    supplierDeletedWithInvoices: '\''✅ Fournisseur supprimé avec'\'',\n    uploadSomeInvoicesToSeeStats: '\''Téléchargez quelques factures pour voir les statistiques'\'',\n    noProductsInInvoices: '\''Aucun produit dans les factures'\'',\n    uploadPhotoDescription: '\''Téléchargez une photo (JPG, PNG) ou un fichier PDF de listes de prix, factures ou catalogues. L'\''IA reconnaîtra automatiquement tous les produits et prix. Vous pouvez télécharger plusieurs fichiers à la fois.'\'',\n    uploadSupplierDataDescription: '\''Téléchargez une photo ou un PDF avec les données des fournisseurs (cartes de visite, listes de contacts, etc.). L'\''IA reconnaîtra automatiquement les données.'\'',\n    uploadOrderDescription: '\''Téléchargez une photo ou un PDF de factures, reçus ou listes de courses. L'\''IA reconnaîtra automatiquement les produits avec quantités et prix pour créer la commande.'\'',\n    from: '\''De'\'',\n    with: '\''avec'\'',\n    together: '\''avec'\'',' src/lib/i18n.ts

# Add German translations after line 1602
sed -i '1602a\    searchInvoicesPlaceholder: '\''Rechnungen nach Nummer, Lieferant oder Notizen suchen...'\'',\n    clickToExpandYearMonth: '\''💡 Klicken Sie auf Jahr/Monat zum Erweitern'\'',\n    goToSuppliersToAddInvoices: '\''Gehen Sie zum Lieferantenbereich, um Rechnungen hinzuzufügen'\'',\n    invoicesCount: '\''Rechnungen'\'',\n    openingInvoiceManagement: '\''📂 Öffnen der Rechnungsverwaltung für'\'',\n    supplierDeletedWithInvoices: '\''✅ Lieferant gelöscht zusammen mit'\'',\n    uploadSomeInvoicesToSeeStats: '\''Laden Sie einige Rechnungen hoch, um Statistiken zu sehen'\'',\n    noProductsInInvoices: '\''Keine Produkte in Rechnungen'\'',\n    uploadPhotoDescription: '\''Laden Sie Foto (JPG, PNG) oder PDF-Datei von Preislisten, Rechnungen oder Katalogen hoch. Die KI erkennt automatisch alle Produkte und Preise. Sie können mehrere Dateien gleichzeitig hochladen.'\'',\n    uploadSupplierDataDescription: '\''Laden Sie Foto oder PDF mit Lieferantendaten (Visitenkarten, Kontaktlisten usw.) hoch. Die KI erkennt die Daten automatisch.'\'',\n    uploadOrderDescription: '\''Laden Sie Foto oder PDF von Rechnungen, Quittungen oder Einkaufslisten hoch. Die KI erkennt automatisch Produkte mit Mengen und Preisen, um die Bestellung zu erstellen.'\'',\n    from: '\''Von'\'',\n    with: '\''mit'\'',\n    together: '\''zusammen mit'\'',' src/lib/i18n.ts

# Add Lithuanian translations after line 1848
sed -i '1848a\    searchInvoicesPlaceholder: '\''Ieškoti sąskaitų faktūrų pagal numerį, tiekėją ar pastabas...'\'',\n    clickToExpandYearMonth: '\''💡 Spustelėkite metai/mėnuo, kad išplėstumėte'\'',\n    goToSuppliersToAddInvoices: '\''Eikite į Tiekėjų skyrių, kad pridėtumėte sąskaitas faktūras'\'',\n    invoicesCount: '\''sąskaitos faktūros'\'',\n    openingInvoiceManagement: '\''📂 Atidaroma sąskaitų faktūrų valdymas'\'',\n    supplierDeletedWithInvoices: '\''✅ Tiekėjas ištrintas kartu su'\'',\n    uploadSomeInvoicesToSeeStats: '\''Įkelkite kelias sąskaitas faktūras, kad matytumėte statistiką'\'',\n    noProductsInInvoices: '\''Nėra produktų sąskaitose faktūrose'\'',\n    uploadPhotoDescription: '\''Įkelkite nuotrauką (JPG, PNG) arba PDF failą su kainų sąrašais, sąskaitomis faktūromis ar katalogais. DI automatiškai atpažins visus produktus ir kainas. Galite įkelti kelis failus vienu metu.'\'',\n    uploadSupplierDataDescription: '\''Įkelkite nuotrauką arba PDF su tiekėjų duomenimis (vizitinės kortelės, kontaktų sąrašai ir kt.). DI automatiškai atpažins duomenis.'\'',\n    uploadOrderDescription: '\''Įkelkite nuotrauką arba PDF su sąskaitomis faktūromis, kvitais ar apsipirkimo sąrašais. DI automatiškai atpažins produktus su kiekiais ir kainomis, kad sukurtų užsakymą.'\'',\n    from: '\''Nuo'\'',\n    with: '\''su'\'',\n    together: '\''kartu su'\'',' src/lib/i18n.ts

echo "Translations added successfully!"